# Generated by Django 3.2.19 on 2023-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('agreed_to_tcs', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
