# Generated by Django 3.2.19 on 2023-06-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_review_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
